### ISSUE TITLE
Before Meeting Checklist [#01]

### ISSUE THREAD

**Issue by adamszs** [adamszs/Junor-Web-Developer-Jobs#1]
- [x] Create github repo
- [x] Create mock up
- [x] Create Github Projects
- [x] Create wiki
